use_frameworks!

platform :ios, '9.0'

target 'HSModules_Example' do
  pod 'HSModules', :path => '../'

  target 'HSModules_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
